# Generated by Django 3.0.7 on 2020-06-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_auto_20200606_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recent_tried',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='available_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.FloatField(default=0),
        ),
    ]
